{% set name = "llama-index" %}
{% set version = "0.13.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_index-{{ version }}.tar.gz
  sha256: 162d64fecbb2d7060b52fe52722395a69da19f8f78b28126520303a36daa57b7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - llama-index-cli >=0.5.0,<0.6
    - llama-index-core >=0.13.5,<0.14
    - llama-index-embeddings-openai >=0.5.0,<0.6
    - llama-index-indices-managed-llama-cloud >=0.4.0
    - llama-index-llms-openai >=0.5.0,<0.6
    - llama-index-readers-file >=0.5.0,<0.6
    - llama-index-readers-llama-parse >=0.4.0
    - nltk >3.8.1

test:
  imports:
    - llama_index
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/run-llama/llama_index
  summary: Interface between LLMs and your data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - pavelzw
