{% set name = "llama-index" %}
{% set version = "0.8.43" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/llama_index-{{ version }}.tar.gz
  sha256: 4472c0f4eba870f9ab3e8bff8ae871f52c7a32b1ee1624c868e11563fef3f824

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - tiktoken >=0.3.3
    - dataclasses-json >=0.5.7,<0.6.0
    - langchain >=0.0.303
    - sqlalchemy >=2.0.15
    - numpy >=1.24.4,<2.0.0
    - tenacity >=8.2.0,<9.0.0
    - openai >=0.26.4
    - pandas >=2.0.3,<3.0.0
    - urllib3 <2
    - fsspec >=2023.5.0
    - typing_inspect >=0.8.0
    - typing-extensions >=4.5.0
    - beautifulsoup4
    - nest-asyncio >=1.5.8,<2.0.0
    - nltk >=3.8.1,<4.0.0
    - tree_sitter_languages

test:
  imports:
    - llama_index
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jerryjliu/llama_index
  summary: Interface between LLMs and your data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
